### PR TITLE
Uniform key row/column sizes

### PR DESCRIPTION
**Pull request by cameronaw13**
Adds the key grid's offset height to the height of the keyboard preventing the last key row from being squished

### CODE REVIEW

**Comment by Vishram1123** [comment]
Don't think this works, the rows are still of the wrong size even with this change on my end... what are your settings?

**Comment by Vishram1123** [comment]
Also, from discussion with other extension devs, this issue seems to come down to rounding error, which I can't really fix so, ya...

**Comment by cameronaw13** [comment]
Yeah this issue is much wider in scope than I had initially thought it was. But, after a lot of testing, I think I've figured it out.

When the GridLayout expands along with the height of the box it will only expand each row in steps based on the number of rows each element spans.

I'm working on a fix that'll disable homogeneous rows and replace the y_expand of each button with a set height based on the type of row its in relative to the height of the box allowing each button to smoothly expand in height.

**Comment by cameronaw13** [comment]
Still need to fix some weirdness in the fullsize and split layouts and apply the same fix for columns but its getting there

**Comment by cameronaw13** [comment]
I had to specify the heights of each key in the top row within `physicalLayouts.json` to calculate `rowSize` without having to hardcode values. I also allowed users to change the keyboard widths/heights in increments of 1 as there's no real reason not to anymore. If you want me to revert these changes lmk.

The core of this pr is pretty much complete just need to figure out why the keys extend beyond the keyboard box in the tenkeyless/fullsize layouts and how to center the keys.

**Comment by cameronaw13** [comment]
Everything should be complete now! Let me know if you have any questions about the code, had to use quite a bit of math.

**Comment by Vishram1123** [comment]
Seems that it still isn't quite working, the keyboard isn't respecting the bounds of its container, and it changes sizing erratically. I'll take another crack at this

**Comment by cameronaw13** [comment]
Yeah I'm not sure how you could solve that issue since the key widths/heights can only be whole integers. Its either have inconsistent margins or have inconsistent row/columns sizes from what I can tell. You could also have the whole keyboard box resize relative to the keys for consistency but then the keyboard would always be slightly bigger/smaller than the screen width/height its set to.

**Comment by Vishram1123** [comment]
I'd rather trade off key sizes being slightly off for consistent margins, because it makes the whole thing look a bit more uniform. I pushed a commit that seems to make the issue less obvious, but there is not really a way to fix it, because integers are required. Sorry

**Pull request closed without merging**
