### PR TITLE
Allow lockscreen use

### PR DESCRIPTION
**Pull request by domgregori**
Added unlock-dialog to session-modes to allow GJS-OSK to work on lockscreen. Note, this is only after first initial login after boot.

### CODE REVIEW

**Comment by Vishram1123** [comment]
Is there a reason why lockscreen use is required?

**Comment by Vishram1123** [comment]
The regular GNOME keyboard works fine when locked, and there is no reason for the extra features offered by gjsosk, so I don't see why lockscreen use is required.

**Comment by Vishram1123** [comment]
The reason why I am asking this is because extension review requires extra provisions to allow for use on the lockscreen, and keyboard events must be disconnected on the lockscreen, so it would be difficult for me to get the extension approved in its current state.

**Comment by Vishram1123** [comment]
@domgregori please tell me if this feature is required; if it is I will have to find a workaround or make the unlock dialog option only available to Github version users

**Comment by domgregori** [comment]
I didn't realize there was more work that needed to be done. I prefer it on the lockscreen because I find the original gnome osk to be glitchy. If you don't want to do all those changes then that's okay. I can just manually change it on my system.

**Comment by Vishram1123** [comment]
Okay, thanks

**Pull request merged**
